# Warning: two different sectors have the same key:
# u'Leasing Services - (LES)',
# u'Legal Services - (LES)',


industry_sectors = [
u'Accounting Services - (ACT)',
 u'Advertising Services - (ADV)',
 u'Agricultural Chemicals - (AGC)',
 u'Agricultural Machinery & Equipment - (AGM)',
 u'Agricultural Services - (AGS)',
 u'Air Conditioning & Refrigeration Equipment - (ACR)',
 u'Aircraft & Parts - (AIR)',
 u'Airport & Ground Support Equipment - (APG)',
 u'Apparel - (APP)',
 u'Architectural/Construction/Eng Svc - (ACE)',
 u'Artwork - (ARW)',
 u'Audio/Visual Equipment - (AUV)',
 u'Automobiles & Light Trucks/Vans - (AUT)',
 u'Automotive Parts & Service Equipment - (APS)',
 u'Aviation Services - (AVS)',
 u'Biotechnology - (BTC)',
 u'Books & Periodicals - (BOK)',
 u'Building Products - (BLD)',
 u'Business Eqpt (other than computers) - (BUS)',
 u'Chemical Production Machinery - (CHM)',
 u'Coal - (COL)',
 u'Comm Vessels & Eqpt (EXCL FISH) - (CVR)',
 u'Commercial Fishing Equipment - (CFE)',
 u'Composite Materials - (CMT)',
 u'Computer & Peripherals - (CPT)',
 u'Computer Services - (CSV)',
 u'Computer Software - (CSF)',
 u'Construction Equipment - (CON)',
 u'Consumer Electronics - (CEL)',
 u'Cosmetics & Toiletries - (COS)',
 u'Defense Industry Equipment - (DFN)',
 u'Dental Equipment - (DNT)',
 u'Drugs & Pharmaceuticals - (DRG)',
 u'Education & Training - (EDS)',
 u'Electrical Power Systems - (ELP)',
 u'Electronic Components - (ELC)',
 u'Electronics Industry Prod/Test Equipment - (EIP)',
 u'Employment Services - (EMP)',
 u'Films Videos & Other Recordings - (FLM)',
 u'Financial Services - (FNS)',
 u'Food Processing & Packaging Eqpt - (FPP)',
 u'Foods Processed - (FOD)',
 u'Footwear - (FOT)',
 u'Forestry & Woodworking Machinery - (FOR)',
 u'Furniture - (FUR)',
 u'General Consumer Goods - (GCG)',
 u'General Industrial Eqpt & Supplies - (GIE)',
 u'General Science & Technology - (GST)',
 u'General Services - (GSV)',
 u'Giftware - (GFT)',
 u'Health Care Services - (HCS)',
 u'Hotel & Restaurant Equipment - (HTL)',
 u'Household Consumer Goods - (HCG)',
 u'Industrial Chemicals - (ICH)',
 u'Information Services - (INF)',
 u'Insurance Services - (INS)',
 u'Investment Service - (INV)',
 u'Iron & Steel - (IRN)',
 u'Jewelry - (JLR)',
 u'Laboratory Scientific Instruments - (LAB)',
 u'Lawn & Garden Equipment - (LGE)',
 u'Leasing Services - (LES)',
 u'Leather & Fur Products - (LFP)',
 u'Legal Services - (LES)',
 u'Machine Tools & Metal Working Eqpt - (MTL)',
 u'Management Consulting Services - (MCS)',
 u'Medical Equipment - (MED)',
 u'Mining Industry Equipment - (MIN)',
 u'Musical Instruments - (MUS)',
 u'Non-Ferrous Metals - (NFM)',
 u'Oil & Gas Field Machinery - (OGM)',
 u'Oil Gas Mineral -(OGS)',
 u'Packaging Eqpt (other than food) - (PKG)',
 u'Paper & Paperboard - (PAP)',
 u'Pet Foods & Supplies - (PET)',
 u'Photographic Equipment - (PHT)',
 u'Plastic Materials & Resin - (PMR)',
 u'Plastics Production Machinery - (PME)',
 u'Pleasure Boats & Accessories - (PLB)',
 u'Pollution Control Equipment - (POL)',
 u'Printing & Graphic Arts Equipment - (PGA)',
 u'Process Controls Industrial - (PCI)',
 u'Pulp & Paper Machinery - (PUL)',
 u'Pumps Valves & Compressors - (PVC)',
 u'Railroad Equipment - (RRE)',
 u'Renewable Energy Equipment - (REQ)',
 u'Robotics - (ROB)',
 u'Security & Safety Equipment - (SEC)',
 u'Sporting Goods & Recreational Equipment - (SPT)',
 u'Telecommunications Equipment - (TEL)',
 u'Telecommunications Services - (TES)',
 u'Textile Fabrics - (TXF)',
 u'Textile Machinery & Equipment - (TXM)',
 u'Textile Products - (TXP)',
 u'Tools Hand & Power - (TLS)',
 u'Toy & Games - (TOY)',
 u'Transportation Srvs (Except Aviation) - (TRN)',
 u'Travel & Tourism Services - (TRA)',
 u'Trucks Trailers & Buses - (TRK)',
 u'Used & Reconditioned Equipment - (USD)',
 u'Veterinary Equipment & Supplies - (VET)',
 u'Water Resources Eqpt & Services - (WRE)',
 u'Yarns - (YAR)']

# This is actually useless, see above comment
industry_keys = [u'ACE',
 u'ACR',
 u'ACT',
 u'ADV',
 u'AGC',
 u'AGM',
 u'AGS',
 u'AIR',
 u'APG',
 u'APP',
 u'APS',
 u'ARW',
 u'AUT',
 u'AUV',
 u'AVS',
 u'BLD',
 u'BOK',
 u'BTC',
 u'BUS',
 u'CEL',
 u'CFE',
 u'CHM',
 u'CMT',
 u'COL',
 u'CON',
 u'COS',
 u'CPT',
 u'CSF',
 u'CSV',
 u'CVR',
 u'DFN',
 u'DNT',
 u'DRG',
 u'EDS',
 u'EIP',
 u'ELC',
 u'ELP',
 u'EMP',
 u'FLM',
 u'FNS',
 u'FOD',
 u'FOR',
 u'FOT',
 u'FPP',
 u'FUR',
 u'GCG',
 u'GFT',
 u'GIE',
 u'GST',
 u'GSV',
 u'HCG',
 u'HCS',
 u'HTL',
 u'ICH',
 u'INF',
 u'INS',
 u'INV',
 u'IRN',
 u'JLR',
 u'LAB',
 u'LES',
 u'LES',
 u'LFP',
 u'LGE',
 u'MCS',
 u'MED',
 u'MIN',
 u'MTL',
 u'MUS',
 u'NFM',
 u'OGM',
 u'OGS',
 u'PAP',
 u'PCI',
 u'PET',
 u'PGA',
 u'PHT',
 u'PKG',
 u'PLB',
 u'PME',
 u'PMR',
 u'POL',
 u'PUL',
 u'PVC',
 u'REQ',
 u'ROB',
 u'RRE',
 u'SEC',
 u'SPT',
 u'TEL',
 u'TES',
 u'TLS',
 u'TOY',
 u'TRA',
 u'TRK',
 u'TRN',
 u'TXF',
 u'TXM',
 u'TXP',
 u'USD',
 u'VET',
 u'WRE',
 u'YAR']

def parse_sectors(string):
    output_list = []
    for sector in industry_sectors:
        if sector in string:
            output_list.append(sector)
    return output_list
